const Products = [
  {
    id: 1,
    title: "Iphone 15",
    description: "white in color",
    price: 565000,
    img: "https://eezepc.com/wp-content/uploads/2023/10/Apple-iPhone-15-Pro-9-1024x1024.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Oppo A17",
    description: "Yellow in color",
    price: 55600,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw3knpRnBalGBaT6hQqUWzFP39Oov2jaHQ1tDf-epfzvScVffSF0OO1Qvv1V90dL61t-Q&usqp=CAU",
    quantity: 1,
  },
  {
    id: 3,
    title: "Redmi C12",
    description: "black in color",
    price: 26800,
    img: "https://www.reliancedigital.in/medias/Xiaomi-11-Prime-Smart-Phone-493178800-i-1-1200Wx1200H-300Wx300H?context=bWFzdGVyfGltYWdlc3wzODAyOHxpbWFnZS9qcGVnfGltYWdlcy9oYzgvaDJhLzk5MTE0MTQyOTI1MTAuanBnfDc0NzBjMWIyZWQ2MjAyNTIzYzNkNmNmZDQ5MzVkNjRiODk2ZWI4ZDg1OTY1OWIwMjM3NDZjMTFhODkxNzlhZWY",
    quantity: 1,
  },
  {
    id: 4,
    title: "Tecno Pova 2",
    description: "Best mobile ever",
    price: 28900,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnEPj7NsPu7PA86RnNZj61rf304LFLiC8fixEOQyLugsSOX4fQSTNqZSV_u1wEmTAQzS8&usqp=CAU",
    quantity: 1,
  },
  {
    id: 5,
    title: "Xiaomi Redmi Note 11",
    description: "black in color",
    price: 67999,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7m-mOfHKHJzVW5xepSdS8hlyUdE3Oy86gxbmhrxPYQ2IBJY213nskJHQBxl32urTnLJo&usqp=CAU",
    quantity: 1,
  },
  {
    id: 6,
    title: "Xiaomi Redmi 9A",
    description: "blue in color",
    price: 15600,
    img: "https://images-na.ssl-images-amazon.com/images/I/71A9Vo1BatL._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Tecno Pova 2",
    description: "black in color",
    price: 35966,
    img: "https://ng.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/43/7447102/1.jpg?9996",
    quantity: 1,
  },
  {
    id: 8,
    title: "Iphone 12",
    description: "Blue mobile ever",
    price: 179999,
    img: "https://images-na.ssl-images-amazon.com/images/I/71hIfcIPyxS._SL1500_.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Xiaomi Redmi Note 12 Pro",
    description: "Cilver in color",
    price: 89999,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkoJJqxfHQhLDM8eOxOqUvarJimQF88r3WSGcFwrF1hoQKCYU0i1w-yLmqeNAYeFicSLI&usqp=CAU",
    quantity: 1,
  },
];
export default Products;
